[versions]
kotlin = "2.0.21"
kotest = "5.9.1"
mockito = "5.14.2"
avro = "1.12.0"
avro-plugin = "1.9.1"
junit = "5.11.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
bom-junit = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter"}
avro = { module = "org.apache.avro:avro", version.ref = "avro" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm", "mockito-core" ]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.69.0"
kotlin-dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
git-semantic-versioning = "org.danilopianini.git-sensitive-semantic-versioning:3.1.7"
avro = { id = "com.github.davidmc24.gradle.plugin.avro", version.ref = "avro-plugin"}
publish = {id="org.danilopianini.publish-on-central", version="5.1.9"}


